[package]
name = "tsp_ga"
version = "0.1.0"
edition = "2024"

[dependencies]
flamegraph = "0.6.8"
kiss3d = "0.35.0"
num-traits = "0.2.19"
rand = { version = "0.9.1", features = ["small_rng"] }
tracing = "0.1.41"
tracing-flame = "0.2.0"
tracing-subscriber = "0.3.19"

[profile.release]
debug = true
